#!/usr/bin/env ruby

$LOAD_PATH << File.join(File.dirname(__FILE__) + '/../lib')

require 'bundler/setup'
require 'pry'
require 'ols'

puts "Welcome to the OLS console (note - you're using pry, not irb)"

Pry.config.prompt = proc { "ols> " }
Pry.start

